### ISSUE TITLE
Call to undefined method Laravel\Nova\Fields\BelongsTo::macro()

### ISSUE THREAD

**Issue by David-Melo** [GeneaLabs/nova-prepopulate-searchable#1]
![image](https://user-images.githubusercontent.com/1429949/45243358-871c2100-b2c1-11e8-9c5b-e5dfb02fe7af.png)

**Comment by alexbowers** [comment]
Unfortunately, this requires Laravel Nova 1.0.13.

Pretty sure I put that as a dependency.

**Comment by David-Melo** [comment]
Thanks for the quick reply. I thought I was on the latest Nova. These releases are coming out faster than I can keep up. Thanks

**Comment by alexbowers** [comment]
You are on the latest one as it stands, I'm waiting on taylor to release the latest one, which has the base field class with Macroable.

**Comment by David-Melo** [comment]
I guess I'll be on the wait for that release. Thanks again.

**Comment by alexbowers** [comment]
@David-Melo It should now be released, can you test it again on the latest version?

**Comment by David-Melo** [comment]
Tried with the latest version installed and it works great. Thanks
