### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by Dontorpedo** [GeneaLabs/nova-prepopulate-searchable#13]
After Installing the package i added populate like this..

`BelongsTo::make('Customer')->searchable()->prepopulate(),`

but nothing happens at all, same as with only searchable, do i miss something?

regards
Denis

**Comment by mikebronner** [comment]
@Dontorpedo  would you guys mind testing version 1.2.0 and let me know if that fixes things for you? Thanks!

**Comment by mikebronner** [comment]
@Dontorpedo I'll close this issue for now. Please feel free to respond if you are still having this problem. Thank you! :)
