### ISSUE TITLE
How to add where clause on query for prepopulate()

### ISSUE THREAD

**Issue by saqueib** [GeneaLabs/nova-prepopulate-searchable#15]
Hi Alex, Please share how do I pass a query to repopulate the search field.

> You may optionally pass through a search query to the prepopulate method, and the keywords passed will be used for the search initially, before resetting the search to being empty (as it currently is).

Above expiation is not clear for me. If you can give some code sample on how to use it that will be great.

I want to load only `active` users.

**Comment by baldhadhaval08** [comment]
@saqueib If you have found a way to pass a query to repopulate then can you please share it here?

**Comment by mikebronner** [comment]
@saqueib @baldhadhaval08  would you guys mind testing version 1.2.0 and let me know if that fixes things for you? Thanks!

**Comment by mikebronner** [comment]
You can pass in a string to the prepopulate method, which basically simulates typing in a search string:

```php
    BelongsTo::make("Archive")
        ->searchable()
        ->prepopulate("test"),
```

This example would only pre-populate the items containing "test" in their display-field.
