### ISSUE TITLE
breaking nullable relations

### ISSUE THREAD

**Issue by jeffreydevreede** [GeneaLabs/nova-prepopulate-searchable#16]
This plugin breaks support of nullable fields. You can still press the `x` to remove the relation but it doesn't actually unset the value so when you click save the value isn't actually `null`.

See https://github.com/laravel/nova-issues/issues/1955 for more information.

**Comment by JoshMoreno** [comment]
In addition, you can't deselect the chosen option to make it null when you aren't using `->searchable()`. The first option is disabled.

```php
BelongsTo::make('User')->nullable(),
```

```html
<option value="" disabled="disabled" selected="selected">Choose User</option>
```
Using Nova `v2.6.1 `

**Comment by mikebronner** [comment]
@jeffreydevreede @JoshMoreno would you guys mind testing version 1.2.0 and let me know if that fixes things for you? Thanks!

**Comment by mikebronner** [comment]
This should now be working as of release 1.2.0. Please make sure to change the repo name in composer.json before updating. (see readme). Thanks!
