### ISSUE TITLE
readonly not working

### ISSUE THREAD

**Issue by davi5e** [GeneaLabs/nova-prepopulate-searchable#19]
The package works fine, but it breaks the readonly method, enabling BelongsTo to change even if it would be expected not to.

Example code to block any update:

```php
BelongsTo::make('User')
    ->searchable()
    ->prepopulate()
    ->readonly(function () {
        return $this->exists;
    })
    ->required(),
```

**Comment by mikebronner** [comment]
@davi5e  would you mind testing version 1.2.0 and let me know if that fixes things for you? Thanks!

**Comment by mikebronner** [comment]
@davi5e This should now be fixed in release 1.3.1. Please make sure to change the repo name in `composer.json` before updating, see readme. Thanks!

**Comment by davi5e** [comment]
Just tested it, it's working!

Thank you for the follow up, I'll be using the package again since this was a huge deal and is now fixed.

**Comment by mikebronner** [comment]
@davi5e Awesome! Thanks for letting me know that its working :) Let me know if you run into any issues. :)
