### ISSUE TITLE
BelongsToMany

### ISSUE THREAD

**Issue by JapSeyz** [GeneaLabs/nova-prepopulate-searchable#2]
Hey,

Are there any plans to introduce this on belongsToMany too, or accepting PR's for it?

**Comment by alexbowers** [comment]
I'll accept PRs for it.

I haven't had any need to set up BelongsToMany in my project yet, so I have not had the need to build it in.

**Comment by JapSeyz** [comment]
Alright, I'll see if I can find some time for it.
