### ISSUE TITLE
Nova 4 Support

### ISSUE THREAD

**Issue by abishekrsrikaanth** [GeneaLabs/nova-prepopulate-searchable#26]
Can you please add support to Nova 4?

**Comment by daanadriaan** [comment]
Any plans on implementing this?

**Comment by mikebronner** [comment]
@abishekrsrikaanth @daanadriaan sorry for the delayed reply. I would be happy to entertain a PR for this, as I am no longer using Nova in my projects.

**Comment by xPhantomNL** [comment]
Has anyone gotten this working with Nova 4 yet? Seen a couple of forks that just updated the composer.json to support Nova 4, but when I do so, the entire field just simply doesn't render anymore and a JS error is thrown in the console.

**Comment by mikebronner** [comment]
@xPhantomNL sorry, not yet. :( 
As I am currently unable to work on support for Nova 4, I will mark this package as abandoned. Sorry for the inconvenience.
