### ISSUE TITLE
Not working after you type and then clear the search field

### ISSUE THREAD

**Issue by maxdb71** [GeneaLabs/nova-prepopulate-searchable#4]
As soon as the form is loaded and you click on the BelongsTo field then the Prepopulate works perfectly.

But, in case you start typing something in the search field and then you delete your input (I mean you clear the string you were writing i.e. you leave the input filed empty again) the Prepopulate doesn't load again all the values.

Thanks,
Max

**Comment by alexbowers** [comment]
Unfortunately, it isn't possible for us to provide those values again, because the searchable component itself has taken over control and decided to remove the values from the list.

This is probably an issue for further upstream on nova-issues repo.
