### ISSUE TITLE
can't install package

### ISSUE THREAD

**Issue by Ange7** [GeneaLabs/nova-prepopulate-searchable#5]
i want install package with:

composer require alexbowers/nova-prepopulate-searchable

but its not working : 

`$ composer require alexbowers/nova-prepopulate-searchable
Using version ^1.0 for alexbowers/nova-prepopulate-searchable
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)         
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - alexbowers/nova-prepopulate-searchable v1.0.1 requires laravel/nova >=1.0.13 -> no matching package found.
    - alexbowers/nova-prepopulate-searchable v1.0.0 requires laravel/nova >=1.0.13 -> no matching package found.
    - Installation request for alexbowers/nova-prepopulate-searchable ^1.0 -> satisfiable by alexbowers/nova-prepopulate-searchable[v1.0.0, v1.0.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
`

my composer.json 

```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.1.3",
        "achalj09/editresource": "^0.0.1",
        "benjaminhirsch/nova-slug-field": "^1.1",
        "caouecs/laravel-lang": "~3.0",
        "coderello/laravel-nova-lang": "^1.0",
        "doctrine/dbal": "^2.8",
        "fideloper/proxy": "^4.0",
        "fourstacks/nova-checkboxes": "^0.1.2",
        "friendsofphp/php-cs-fixer": "^2.13",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "5.7.*",
        "laravel/nova": "*",
        "laravel/tinker": "^1.0",
        "maatwebsite/laravel-nova-excel": "^1.1",
        "predis/predis": "^1.1",
        "shivanshrajpoot/nova-create-or-add": "^0.0.1",
        "silvanite/novafieldcheckboxes": "^1.1"
    },
    "require-dev": {
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "phpunit/phpunit": "^7.0"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

**Comment by alexbowers** [comment]
How are you installing Laravel Nova?

Can you share the version of nova you're using?

**Comment by chrisbjr** [comment]
@alexbowers there are different ways of installing Nova. I suggest removing the requirement of the package in `composer.json`.

**Comment by alexbowers** [comment]
Unfortunately, because this only works from version 1.0.13 onwards in Nova, I will be keeping the composer requirement.

The dependency we have is:

```
Add Macroable to Field.
```

**Comment by alexbowers** [comment]
For this package to be usable, you must also have installed nova via Composer.

For details on how to do that:

https://nova.laravel.com/docs/1.0/installation.html#installing-nova-via-composer
