### ISSUE TITLE
Creating from resource

### ISSUE THREAD

**Issue by dddeeemmmooonnn** [GeneaLabs/nova-prepopulate-searchable#6]
Problem 3: https://github.com/laravel/nova-issues/issues/930
Same in belongsTo, when prepopulate installed, works when deleted.
Update, please

**Comment by alexbowers** [comment]
Hi sorry @dddeeemmmooonnn I completely missed this, please can you elaborate on what you mean, if it is still an issue for you.

Thanks.

**Comment by dddeeemmmooonnn** [comment]
Hi, just rewrite from new nova sources. I have already rewrote myself, and also MorphTo

**Comment by mikebronner** [comment]
@dddeeemmmooonnn  would you mind testing version 1.2.0 and let me know if that fixes things for you? Thanks! I do believe it is fixed, so please re-open if it doesn't work for you.
